Author: @Alex Qian(wenzhang@ualberta.ca)
# Welcome to your interactive tutorial of Jupyter notebook, Numpy and OpenCV

## Jupyter notebook
* launch
* run a cell
* code <---> markdown
* toolbar
* command palette
* keyboard shortcuts
* (magic keywords)

### launch
`jupyter notebook` or `jupyter notebook tutorial.ipynb` in the terminal.

Potential error for the dependency. Install all the packagees.

If you are using my Starter-Kit, use `source activate robo` on Mac OS/ Linux or `activate robo` on Windows

The server runs at http://localhost:8888 by default.

### run a cell
Add code in a cell and use "shift + enter" to run it.

### Quiz:
Print Hello World

Hello World!


### cell types
Only code cells and markdown cells will be covered in this tutorial.

You just made a code cell. Let's create a markdown cell.

There can be 
# Header 1
## Header 2
### Header 3
 [Author's Github profile](https://github.com/AlexQian97)
 
 _italics_ or *italics*
 
 __bold__ or **bold**
$$
y = \frac{a}{b+c}
$$
I am not good at LaTex, I am not goint to continue on the math expression. Anyway, you can always find resources on Google.

### toolbar
Just go through all icons
* The anachronistic symbol for "save," the floppy disk. Saves the notebook!
* The + button creates a new cell
* Then, buttons to cut, copy, and paste cells.
* Run, stop, restart the kernel
* Cell type: code, Markdown, raw text, and header
* Command palette (see next)
* Cell toolbar, gives various options for cells such as using them as slides

Three cells below are intentionally left empty for you to test these functions.

### command palette
The little keyboard is the command palette. This will bring up a panel with a search bar where you can search for various commands. This is really helpful for speeding up your workflow as you don't need to search around in the menus with your mouse. Just open the command palette and type in what you want to do. For instance, if you want to merge two cells:

Just one more thing, I wish you could add a html file of your notebook so that people do not have to open your notebook with command line to just have a look.

My tutorial is just a crush course, if you want to learn more about Jupyter notebook. This is the offical website of [Jupyter](http://jupyter.org). You can find documents and tutorial about Jupyter on it.

# Good job, you have done the Jupyter notebook tutorial. Let's do some Numpy.
Numpy is a library adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In short, a high-performace math library.

First, let's make a matrix.

In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


What?! You think that is too fast?! Okay, let's start with array because matrix is just a array of arrays.

In [5]:
import numpy as np
# This is a list
im_list = [1, 2, 3]
# This is a numpy array
im_np_array = np.array(im_list)
print(im_np_array)
print(type(im_np_array))

[1 2 3]
<type 'numpy.ndarray'>


### Quiz:
create a list of your birthday [yyyy, mm, dd] and make it a numpy array.

In [9]:
birthday = [1997, 6, 16]
birthday = np.array(birthday)

Good job, you just created your first numpy array. Let's have a closer look at numpy array.

In [10]:
birthday.dtype

dtype('int64')