Author: @Alex Qian(wenzhang@ualberta.ca)
# Welcome to your interactive tutorial of Jupyter notebook, Numpy and OpenCV

## Jupyter notebook
* launch
* run a cell
* code <---> markdown
* toolbar
* command palette
* keyboard shortcuts
* (magic keywords)

### launch
`jupyter notebook` or `jupyter notebook tutorial.ipynb` in the terminal.

Potential error for the dependency. Install all the packagees.

If you are using my Starter-Kit, use `source activate robo` on Mac OS/ Linux or `activate robo` on Windows

The server runs at http://localhost:8888 by default.

### run a cell
Add code in a cell and use "shift + enter" to run it.

### Quiz:
Print Hello World

Hello World!


### cell types
Only code cells and markdown cells will be covered in this tutorial.

You just made a code cell. Let's create a markdown cell.

There can be 
# Header 1
## Header 2
### Header 3
 [Author's Github profile](https://github.com/AlexQian97)
 
 _italics_ or *italics*
 
 __bold__ or **bold**
$$
y = \frac{a}{b+c}
$$
I am not good at LaTex, I am not goint to continue on the math expression. Anyway, you can always find resources on Google.

### toolbar
Just go through all icons
* The anachronistic symbol for "save," the floppy disk. Saves the notebook!
* The + button creates a new cell
* Then, buttons to cut, copy, and paste cells.
* Run, stop, restart the kernel
* Cell type: code, Markdown, raw text, and header
* Command palette (see next)
* Cell toolbar, gives various options for cells such as using them as slides

Three cells below are intentionally left empty for you to test these functions.

### command palette
The little keyboard is the command palette. This will bring up a panel with a search bar where you can search for various commands. This is really helpful for speeding up your workflow as you don't need to search around in the menus with your mouse. Just open the command palette and type in what you want to do. For instance, if you want to merge two cells:

Just one more thing, I wish you could add a html file of your notebook so that people do not have to open your notebook with command line to just have a look.

My tutorial is just a crush course, if you want to learn more about Jupyter notebook. This is the offical website of [Jupyter](http://jupyter.org). You can find documents and tutorial about Jupyter on it.

# Good job, you have done the Jupyter notebook tutorial. Let's do some Numpy.
Numpy is a library adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In short, a high-performace math library.

First, let's make a matrix.

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


What?! You think that is too fast?! Okay, let's start with array because matrix is just a array of arrays.

In [2]:
import numpy as np
# This is a list
im_list = [1, 2, 3]
# This is a numpy array
im_np_array = np.array(im_list)
print(im_np_array)
print(type(im_np_array))

[1 2 3]
<type 'numpy.ndarray'>


### Quiz:
create a list of your birthday [yyyy, mm, dd] and make it a numpy array.

In [3]:
birthday = [1997, 6, 16]
birthday = np.array(birthday)

Good job, you just created your first numpy array. Let's have a closer look at numpy array.

In [4]:
birthday.dtype

dtype('int64')

Append a float number GPA to it using `np.append([list], [list])`

In [13]:
np.append(birthday, 4.0)

array([ 1997.,     6.,    16.,     4.])

In [14]:
birthday.dtype

dtype('int64')

Obviously, Numpy Array can only store one and only one datatype.

### Then, let's do some basic math. Run the following cells and try to understand the logic behind Numpy.

In [36]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [17]:
# + an array
a + b

array([20, 31, 42, 53])

In [19]:
# - an array
a - b

array([20, 29, 38, 47])

In [20]:
# *
a * b

array([  0,  30,  80, 150])

In [22]:
# /
a / b

/Users/pro/.local/lib/python2.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in divide
  


array([ 0, 30, 20, 16])

### matrix operations

In [24]:
# what if the size if not same
c = np.arange(3)
print(c)
print("=========")
a + c

[0 1 2]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

Obviously, all operations are elementwise if both a and b are numpy arrays with the same size.

In [25]:
a + 1

array([21, 31, 41, 51])

In [26]:
a * 2

array([ 40,  60,  80, 100])

Tell them that your English is too poor to describe it.

We can talk about matrix after you understand array.

A matrix is just an array of arrays

In [31]:
Im_matrix = np.array([[1, 2],
                      [3, 4]])
print(Im_matrix)
print(Im_matrix.shape)
print(Im_matrix.dtype)

[[1 2]
 [3 4]]
(2, 2)
int64


In [45]:
Im_matrix = np.arange(4).reshape(2, 2)
print(Im_matrix)

[[0 1]
 [2 3]]


### Quiz: create a matrix of any size.
I know this quiz is dumb but I just want to make sure you are still with me.

### The following methods are useful when dealing with masks. ATTENTION.

In [33]:
ones = np.ones((2, 3), dtype=int)
print(ones)

[[1 1 1]
 [1 1 1]]


In [35]:
zeros = np.zeros((2, 3), dtype=int)
print(zeros)

[[0 0 0]
 [0 0 0]]


In [43]:
random_noise = np.random.random((2, 3))
print(random_noise)
print(random_noise.sum())
print("================")
print(random_noise.sum(axis=0))
print(random_noise.sum(axis=1))
print("================")
print(random_noise.min())
print(random_noise.max())

[[ 0.47598413  0.66879107  0.76142081]
 [ 0.69654489  0.90818469  0.63153504]]
4.14246063513
[ 1.17252903  1.57697576  1.39295585]
[ 1.90619601  2.23626462]
0.475984133943
0.908184689532


In [40]:
spaced = np.linspace(0, 10, 5)
print(spaced)

[  0.    2.5   5.    7.5  10. ]


### matrix operations

In [50]:
a = b = np.arange(4).reshape(2,2)
print(a)
a.dot(b)

[[0 1]
 [2 3]]


array([[ 2,  3],
       [ 6, 11]])

In [55]:
a = [1, 2, 3]
b = [4, 5 ,6]
np.cross(a, b)

array([-3,  6, -3])

In [56]:
a = np.array([1, 2, 3])
b = np.array([4, 5 ,6])
np.cross(a, b)

array([-3,  6, -3])

### Indexing, Slicing, Iterating

In [58]:
a = np.arange(10) ** 3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [59]:
a[2]

8

In [60]:
a[2:5]

array([ 8, 27, 64])

In [61]:
a[:6:2]

array([ 0,  8, 64])

In [63]:
Im_matrix = np.arange(25).reshape(5, 5)
print(Im_matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [65]:
Im_matrix[2:5, 2:5]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

## Congratulations, you have done the Numpy totorial. After that, we can do some computer vision with OpenCV.